### ISSUE TITLE
Building on macOS ends up without any fabric backend

### ISSUE THREAD

**Issue by mathstuf** [mochi-hpc/mochi-spack-packages#3]
When using this spec:

```
mochi-thallium@main^libfabric fabrics=tcp,rxm
```

on macOS, it seems that the `tcp` backend doesn't get found:

```
(   0.003s) [main thread     ]         vtkSession.cxx:114   INFO| vtkThalliumSession (0x12be1baf0): initializing session (tcp)
# [157603.616864] mercury->fatal: [error] /var/folders/d1/wztg0fxx11qd_04b1y78d1j00000gq/T/svc-dashboard/spack-stage/spack-stage-mercury-2.1.0rc4-kxigqkffcpu4pbu5qhzapysbhc4j5yol/spack-src/src/na/na.c:327
 # NA_Initialize_opt(): No suitable plugin found that matches tcp
[error] Could not initialize hg_class
libc++abi: terminating with uncaught exception of type thallium::margo_exception: […/spack/src/opt/spack/darwin-bigsur-m1/apple-clang-13.0.0/mochi-thallium-main-uzkc7xrtp5qut5mp3vlpkm4xlawd5z7v/include/thallium/engine.hpp:180][margo_init_ext] Could not initialize Margo
Loguru caught a signal: SIGABRT
```

The same spec on Linux works just fine. Is there something missing in our spec or is the Spack package not plumbing the `fabrics=` request around properly? Or is the `fabrics=` request not even correct?

**Comment by mdorier** [comment]
I believe the `tcp` provider doesn't work on Mac OS. You need to use `socket` (or `sockets`, I don't remember).
@soumagne can you confirm?

**Comment by utkarshayachit** [comment]
What's is a consistent protocol to use, in that case, so client and server on linux and mac resp. (or vice-versa) can talk to each other? Would that be `sockets`?

**Comment by mdorier** [comment]
You can try `ofi+tcp` though I think Jerome @soumagne once told me this didn't work on Mac. If it doesn't work, `ofi+sockets` should work (you need to add `sockets` in the list of fabrics).

**Comment by carns** [comment]
@utkarshayachit this might be a good question to pose to the libfabric mailing list.  The tcp provider has had a good bit of development activity over the past year or so, so it's possible that the supported providers on Mac OS have evolved a bit? If the libfabric maintainers recommend a particular combination, then we can help make sure that combination works well with Mercury and Mochi.

**Comment by soumagne** [comment]
Mercury actually has a check that prevents you from trying to use `tcp` on MacOS. We added that check so that users would get an error that is a bit more friendly, you should actually see something like that when trying to use `ofi+tcp`:
```
# Using info string: ofi+tcp://
# [832820.371474] mercury->cls: [error] /Users/jsoumagne/workspace/mercury/source/src/na/na_ofi.c:3787
 # na_ofi_check_protocol(): Protocol "tcp" not supported on macOS, please use "sockets" instead
# [832820.371490] mercury->fatal: [error] /Users/jsoumagne/workspace/mercury/source/src/na/na.c:311
 # NA_Initialize_opt(): Specified class name does not support requested protocol
# [832820.371497] mercury->na_test: [error] /Users/jsoumagne/workspace/mercury/source/Testing/na/na_test.c:426
 # NA_Test_init(): Could not initialize NA
# [832820.371539] mercury->hg_test: [error] /Users/jsoumagne/workspace/mercury/source/Testing/mercury_test.c:489
 # HG_Test_init(): NA_Test_init() failed (NA_PROTOCOL_ERROR)
# [832820.371549] mercury->hg_test: [error] /Users/jsoumagne/workspace/mercury/source/Testing/test_server.c:133
 # main(): HG_Test_init() failed
```
