### ISSUE TITLE
Please make these packages available on the official Spack repo.

### ISSUE THREAD

**Issue by hyoklee** [mochi-hpc/mochi-spack-packages#8]
I wish I could install Mochi packages directly from

https://github.com/spack/spack/tree/develop/var/spack/repos/builtin/packages/

I'm working on [Hermes ](https://github.com/HDFGroup/hermes) project that relies on Mochi. I'd like to publish Hermes package to the official Spack once Mochi packages are available from the official Spack repo.

Thanks,

**Comment by mdorier** [comment]
Hi @hyoklee, which Mochi libraries are you using? So far we have only upstreamed margo in spack, but maybe we upstream some other libraries.

**Comment by hyoklee** [comment]
Hermes uses mochi-thallium without cereal and mercury without bootsys:

```THALLIUM_SPEC="mochi-thallium~cereal@${THALLIUM_VERSION} ^mercury~boostsys"```


You can check more details from

   https://github.com/HDFGroup/hermes/blob/master/ci/install_deps.sh

Thanks!

**Comment by hyoklee** [comment]
I'm new to Hermes project so I'll defer your question to Hermes gurus.
@ChristopherHogan or @gheber, do you know why Cereal was turned off for Hermes?

**Comment by mdorier** [comment]
I have a PR in spack to add mochi-thallium: https://github.com/spack/spack/pull/29722

**Comment by hyoklee** [comment]
Thanks, @mdorier !

**Comment by mdorier** [comment]
The mochi-thallium package was merged upstream, so you should be able to get it by updating your spack installation.
